name: Build, Test, and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test -v ./...

    - name: Run test coverage
      run: go test -coverprofile=coverage.out ./...

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.out

    - name: Run vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        severity: 'HIGH,CRITICAL'

    - name: Build binary
      run: |
        go build -o endoflife_exporter main.go

    - name: Create tar.gz package
      run: |
        tar -czvf endoflife_exporter_${{ github.ref_name }}.tar.gz endoflife_exporter

    - name: Upload release asset
      uses: actions/upload-artifact@v2
      with:
        name: endoflife_exporter_${{ github.ref_name }}.tar.gz
        path: endoflife_exporter_${{ github.ref_name }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: endoflife_exporter_${{ github.ref_name }}.tar.gz

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: endoflife_exporter_${{ github.ref_name }}.tar.gz